### ISSUE TITLE
unzip package is missing

### ISSUE THREAD

**Issue by LukaBanovic** [edgeimpulse/balena-cam-tinyml#1]
Testing on RPi 3 Model B v1.2: the unzip package used in downloadWasm.sh is not installed by default due to which curl request part failed, therefore default WASM classifier was used.

Fixed by adding apt-get install unzip in Dockerfile.template

**Comment by aureleq** [comment]
Hi Luka,

Thanks for reporting that. We've added the unzip package to the Dockerfile for 32 bits platforms.

Aurelien
